apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1) 공통 리소스(base)를 import
resources:
  - ../../base/backend
  - ../../base/frontend
  - sealedsecret-backend-env.yaml
  - sealedsecret-frontend-env.yaml

# 2) 프로덕션 전용 패치 파일들
patches:
  - path: patches/backend-replicas.yaml
    target:
      kind: Deployment
      name: backend
  - path: patches/backend-env.yaml
    target:
      kind: Deployment
      name: backend
  - path: patches/frontend-replicas.yaml
    target:
      kind: Deployment
      name: frontend
  - path: patches/frontend-env.yaml
    target:
      kind: Deployment
      name: frontend
  # - path: patches/frontend-env.yaml
  #   target:
  #     kind: Deployment
  #     name: frontend
# (선택) 환경별 이미지 태그 override
# images:
#   - name: mydockerhubuser/spring-backend
#     newTag: prod-latest
#   - name: mydockerhubuser/react-frontend
#     newTag: prod-latest

# (선택) 프로덕션 전용 ConfigMap 생성
# configMapGenerator:
#   - name: prod-common-config
#     literals:
#       - LOG_LEVEL=ERROR
