apiVersion: v1
kind: Service
metadata:
  name: spring-frontend
spec:
  type: NodePort
  selector:
    app: spring-frontend # ← 이 부분이 있어야 합니다
  ports:
    - name: http
      port: 80
      targetPort: 5173
      nodePort: 30081
