apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/frontend
  - sealedsecret-frontend-env.yaml
patches:
  - path: frontend-replicas.yaml
    target:
      kind: Deployment
      name: spring-frontend
  - path: frontend-env.yaml
    target:
      kind: Deployment
      name: spring-frontend
