apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/beming-dev/infra-repo.git
    path: overlays/production
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
