apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/beming-dev/stock-simulator-cicd.git
    path: overlays/production
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
