apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/backend
  - ../sealedsecret-backend-env.yaml
patches:
  - path: ../patches/backend-replicas.yaml
    target:
      kind: Deployment
      name: spring-backend
  - path: ../patches/backend-env.yaml
    target:
      kind: Deployment
      name: spring-backend
