apiVersion: v1
kind: Service
metadata:
  name: spring-backend
spec:
  type: NodePort
  selector:
    app: spring-backend # ← 이 부분이 있어야 합니다
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
