apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  labels:
    app: spring-backend
spec:
  type: ClusterIP
  selector:
    app: spring-backend
  ports:
    - name: http
      port: 80         # 클러스터 내부에서 호출할 포트
      targetPort: 8080 # Deployment의 containerPort와 매핑
