resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - frontend-deploy.yaml
  - frontend-svc.yaml
  - namespace-frontend.yaml
images:
  - name: beming/stock-simulator-back
    newTag: f7ddb7b401ae5d22842f4140e4974cd353fdb4de
  - name: beming/stock-simulator-front
    newTag: 948923617e9695ccf19fd084e2e5f04a18d9a654
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
